fix #836
bioconda/bioconda-utils pull request #838
Opened 2023-02-24 11:16 UTC by jpfeuffer

completely untested but it is an obvious bug.
If you want to change the package dirs earlier in the code somewhere, please suggest changes

2023-02-26 17:02 UTC, jpfeuffer commented
@bgruening @daler Ready to review. Somehow I cannot request it from the normal UI.

2023-02-27 17:56 UTC, daler commented
@jpfeuffer just to clarify, is OpenMS is using bioconda-utils for internal builds?

2023-02-27 18:11 UTC, daler commented
Ah, ok. Can you point to where (and how) you are calling it then? I bet if it's not *exactly* how we call it in bioconda-recipes then that might introduce behavior that we don't otherwise test for.

2023-02-27 18:19 UTC, jpfeuffer commented
Sure! Yes, you might not be using the `--docker`-specific `--pkg_dir` option to specify a directory to be mounted into the docker container. We use it, so we can reuse already-built packages for the next run and generally have access to the finished packages after the build. I did not check if we can change the upload behavior otherwise that would have been an alternative.

```bash
# output must be a valid conda "channel" (otherwise I think I encountered problems)
mkdir -p output/noarch
touch output/noarch/repodata.json
conda activate bioconda
mamba update -y bioconda-utils
conda index output

git clone github.com/bioconda/bioconda-recipes && cd bioconda-recipes
bioconda-utils build --docker --pkg_dir $WORKSPACE/output --packages openms-meta
bioconda-utils build --docker --pkg_dir $WORKSPACE/output --packages pyopenms
```

Note: you cannot run them together because of #751

2023-02-27 22:05 UTC, daler commented
So the default behavior is for `--pkg_dir` to not be set, which in turn defaults to the identified `conda-build` directory on the host, which is where the built recipes will be copied to and mounted read-only into the container. So the default behavior does, I think, what you are aiming to do.

Does it work if you remove the `--pkg_dir` arg?

2023-02-27 22:12 UTC, jpfeuffer commented
Yes, I think it works without `--pkg_dir` but somehow we ended up using a subfolder in the workspace (persistency, permission reasons I guess). We might be able to reevaluate the thing but I think it would be great if the build also works with `--pkg_dir`.

2023-02-27 22:19 UTC, daler commented
I _think_ it would be ok to merge as-is since we don't use `--pkg_dir` anywhere in production, but merging without tests always makes me nervous. And there are currently bigger issues to resolve that affect the entire channel (and very limited time to do so). 

Can you write a test for this in the `test` dir, that fails in master branch but passes with your addition?

2023-02-28 10:33 UTC, jpfeuffer commented on test/test_utils.py
> +@pytest.fixture(scope='module', ids=IDS)
@daler I have no idea how to see if this actually was tested and what its output was.

2023-02-28 10:34 UTC, jpfeuffer commented on test/test_utils.py
> +    for pkg in recipes_fixture.pkgs['one']:
I think instead of using this "ensure_missing" one could just check the BuildResult returned by build.

2023-02-28 18:01 UTC, jpfeuffer commented
@daler Ready. I am 90% sure it will fail on master.

2023-03-03 14:45 UTC, jpfeuffer commented
@daler Do you need anything else?

2023-03-20 13:31 UTC, timosachsenberg commented
Hi, has there been any progress with this PR?

2023-03-24 22:14 UTC, johanneskoester requested changes

2023-03-24 22:14 UTC, johanneskoester commented on bioconda_utils/build.py
> +                        platform = "linux"
The platform can be inferred from `RepoData().native_platform()`.

2023-03-24 22:14 UTC, johanneskoester commented on bioconda_utils/build.py
> +                        platform = "linux"
Also, make sure that you indent only with 4 spaces.

2023-04-01 09:14 UTC, poshul commented
`FAILED test/test_utils.py::test_single_build_pkg_dir - AssertionError: bug: ensure to load config before instantiating RepoData.
ERROR test/test_utils.py::test_single_build_only[with docker] - AssertionError: bug: ensure to load config before instantiating RepoData.`

2023-04-07 17:10 UTC, jpfeuffer commented
Sorry, I don't know what that means. I merely added the review suggestion. I guess this error is also why the suggested code was not used in the place where I copied it from 🤷.
I guess we have to wait for further suggestions..

2023-04-14 08:08 UTC, timosachsenberg commented
any update here?

2023-10-25 09:18 UTC, poshul commented
@johanneskoester @daler any updates?

2024-11-19 14:49 UTC, timosachsenberg commented
any news?

2024-11-19 15:12 UTC, bgruening commented on bioconda_utils/build.py
> +            if (docker_builder.pkg_dir is not None):
```suggestion
            if docker_builder.pkg_dir is not None:
```

2024-11-19 17:13 UTC, bgruening approved these changes
Thanks everyone!

2024-11-19 17:14 UTC, merged