swaps from github API to expanding the assets
bioconda/bioconda-utils pull request #907
Opened 2023-07-28 18:19 UTC by holtjma

This is basically a patch to fix a new issue (described here: https://github.com/bioconda/bioconda-recipes/issues/42176) that was introduced by myself here: https://github.com/bioconda/bioconda-utils/pull/896.

The primary cause is that the GitHub API is rate limited (which I was not aware of), so autobump basically blows through the limits quickly and then subsequent calls automatically fail.  Of course, this means that the tools we were hoping to see get autobumped are not.

This patch basically removes the original patch (which uses a single GitHub API call) and replaces it with an approach that basically "expands" the release webpage to find the assets.  See https://github.com/bioconda/bioconda-utils/issues/895 for more details on how the URLs are masked and the expansion pattern.

Couple other notes:
* I added an `IncludeFragmentParser` that is basically identical to the `HrefParser` except it is looking for tags with this pattern: `<include-fragment src="http://url/of/interest" ...>`
* The general expansion logic is:
  * Pull the full release page
  * Search for `<include-fragment ...>` tags
  * Iteratively pull these looking for the main link URL of interest 
  * Break the above iteration early if the current version is identified
* This should no longer use the GitHub API, I'm unaware of other rate limiters for these URLs (🤞that none are hidden...)

Pinging @dpryan79 and @johanneskoester as you both reviewed the last related PR.  Sorry that the previous PR injected a rate limit issue!

2023-07-29 02:36 UTC, holtjma commented
That failure seems odd, almost looks like it froze for some reason when I checked timestamps.

2023-07-31 14:24 UTC, holtjma commented
Looks like checks passed now, just waiting on feedback from maintainers on the change

2023-08-09 07:43 UTC, johanneskoester approved these changes

2023-08-09 07:45 UTC, johanneskoester requested changes
Looks good to me! Thanks a lot! Of course I would prefer the API as we never know what the do with the page layout. Maybe we can keep the API code as well, and just have both options? This way, we could later decide to use a rate limiter or maybe convince github of some higher limits without having to implement everything again.

2023-08-09 10:25 UTC, jmarshall commented
See my comment on bioconda/bioconda-recipes#42176: if we store etags from the API calls, it’d be trivial to avoid the rate limits.

2023-08-09 15:06 UTC, holtjma commented
> Maybe we can keep the API code as well, and just have both options? This way, we could later decide to use a rate limiter or maybe convince github of some higher limits without having to implement everything again.

@johanneskoester I moved the API version and the expanded asset version into subroutines that are invoked.  John's point about the etags / last modified is probably the best way to handle the API in the future, but I'm not sure what long-term memory access autobump would have to retain that info.  Those modifications could probably exist in a future PR though.

Tests appear to be passing again, and I double checked that results were the same with hiphase and pbfusion recipes.

2023-08-16 15:49 UTC, johanneskoester approved these changes

2023-08-16 15:50 UTC, merged